---
- name: PENJODOHAN DAN AKSI SWITCHOVER STATUS
  hosts: localhost
  vars:
    db1_ip: "192.168.1.211"
    db2_ip: "192.168.1.222"
  tasks:

    - name: Log kondisi dari semua profile
      debug:
        msg:
          - "DB1 @ IDFGICU1: {{ hostvars[db1_ip]['db1_cu1_role'].stdout }}"
          - "DB2 @ IDFGICU1: {{ hostvars[db2_ip]['db2_cu1_role'].stdout }}"
          - "DB1 @ IDFGISU1: {{ hostvars[db1_ip]['db1_su1_role'].stdout }}"
          - "DB2 @ IDFGISU1: {{ hostvars[db2_ip]['db2_su1_role'].stdout }}"

    # === Kondisi IDFGICU1 ===
    - name: Switchover Check - .IDFGICU1 DB1 Primary
      when:
        - "'PRIMARY' in hostvars[db1_ip]['db1_cu1_role'].stdout"
        - "'PHYSICAL STANDBY' in hostvars[db2_ip]['db2_cu1_role'].stdout"
      block:
        - name: Check switchover_status dari DB1 dan DB2
          import_playbook: check_switchover_status.yml
          vars:
            source_db: "{{ db1_ip }}"
            target_db: "{{ db2_ip }}"
            profile_env: ".IDFGICU1"

    - name: Switchover Check - .IDFGICU1 DB2 Primary
      when:
        - "'PRIMARY' in hostvars[db2_ip]['db2_cu1_role'].stdout"
        - "'PHYSICAL STANDBY' in hostvars[db1_ip]['db1_cu1_role'].stdout"
      block:
        - name: Check switchover_status dari DB2 dan DB1
          import_playbook: check_switchover_status.yml
          vars:
            source_db: "{{ db2_ip }}"
            target_db: "{{ db1_ip }}"
            profile_env: ".IDFGICU1"

    # === Kondisi IDFGISU1 ===
    - name: Switchover Check - .IDFGISU1 DB1 Primary
      when:
        - "'PRIMARY' in hostvars[db1_ip]['db1_su1_role'].stdout"
        - "'PHYSICAL STANDBY' in hostvars[db2_ip]['db2_su1_role'].stdout"
      block:
        - name: Check switchover_status dari DB1 dan DB2
          import_playbook: check_switchover_status.yml
          vars:
            source_db: "{{ db1_ip }}"
            target_db: "{{ db2_ip }}"
            profile_env: ".IDFGISU1"

    - name: Switchover Check - .IDFGISU1 DB2 Primary
      when:
        - "'PRIMARY' in hostvars[db2_ip]['db2_su1_role'].stdout"
        - "'PHYSICAL STANDBY' in hostvars[db1_ip]['db1_su1_role'].stdout"
      block:
        - name: Check switchover_status dari DB2 dan DB1
          import_playbook: check_switchover_status.yml
          vars:
            source_db: "{{ db2_ip }}"
            target_db: "{{ db1_ip }}"
            profile_env: ".IDFGISU1"
