---
- name: Pengecekan ENV .IDFGICU1
  hosts: localhost
  tasks:
    - name: "Pengecekan siapa PRIMARY dan STANDBY untuk .IDFGICU1"
      debug:
        msg: >
          DB1 = {{ 'PRIMARY' if 'PRIMARY' in hostvars['192.168.1.211']['db1_role'] else 'STANDBY' }},
          DB2 = {{ 'PRIMARY' if 'PRIMARY' in hostvars['192.168.1.222']['db2_role'] else 'STANDBY' }}

- name: Pengecekan ENV .IDFGISU1
  hosts: localhost
  tasks:
    - name: "Pengecekan siapa PRIMARY dan STANDBY untuk .IDFGISU1"
      debug:
        msg: >
          DB1 = {{ 'PRIMARY' if 'PRIMARY' in hostvars['192.168.1.211']['db1_role'] else 'STANDBY' }},
          DB2 = {{ 'PRIMARY' if 'PRIMARY' in hostvars['192.168.1.222']['db2_role'] else 'STANDBY' }}
