---
- name: Pengecekan Kondisi DB (Dev & UAT)
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Tampilkan hasil dari .bash_profile
      debug:
        msg: "Role DB dari .bash_profile: {{ db_role_profile }}"

    - name: Tampilkan hasil dari .bashrc
      debug:
        msg: "Role DB dari .bashrc: {{ db_role_bashrc }}"

    - name: Cek role .bash_profile (Dev Primary & UAT Standby)
      set_fact:
        switchover_action: "DEV_TO_UAT"
      when:
        - "'PRIMARY' in db_role_profile"
        - "'STANDBY' in db_role_bashrc"

    - name: Cek role .bash_profile (UAT Primary & Dev Standby)
      set_fact:
        switchover_action: "UAT_TO_DEV"
      when:
        - "'STANDBY' in db_role_profile"
        - "'PRIMARY' in db_role_bashrc"

    - name: Tampilkan action yang akan diambil
      debug:
        msg: "Action switchover yang dipilih: {{ switchover_action | default('TIDAK ADA ACTION') }}"
