---
- name: Pengecekan Kondisi DB1 dan DB2
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Debug DB1 & DB2 roles
      debug:
        msg:
          - "DB1 Primary: {{ db1_primary | default('') }}"
          - "DB1 Standby: {{ db1_standby | default('') }}"
          - "DB2 Primary: {{ db2_primary | default('') }}"
          - "DB2 Standby: {{ db2_standby | default('') }}"

    - name: Tentukan pasangan untuk switchover (CU1)
      set_fact:
        source_db: "{{ db1_primary if db1_primary is defined else db2_primary }}"
        target_db: "{{ db2_standby if db1_primary is defined else db1_standby }}"
      when: db1_primary is defined or db2_primary is defined

    - name: Tentukan pasangan untuk switchover (SU1)
      set_fact:
        source_db: "{{ db1_primary if db1_primary is defined else db2_primary }}"
        target_db: "{{ db2_standby if db1_primary is defined else db1_standby }}"
      when: db1_primary is defined or db2_primary is defined

    - name: Debug hasil penjodohan
      debug:
        msg:
          - "Source DB: {{ source_db }}"
          - "Target DB: {{ target_db }}"
