---
- name: Cek ROLE database di DB1 dan DB2 (.IDFGICU1 dan .IDFGISU1)
  hosts: 192.168.1.211,192.168.1.222
  gather_facts: no
  vars:
    hostmap:
      192.168.1.211: db1
      192.168.1.222: db2

  tasks:

    - name: Cek role di ENV .IDFGICU1
      shell: |
        source ~/.IDFGICU1
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin
        echo "SET HEADING OFF FEEDBACK OFF; SELECT database_role FROM v\$database;" | sqlplus -s / as sysdba | tr -d '[:space:]'
      register: role_cu1
      ignore_errors: true

    - name: Display hasil role .IDFGICU1 (stdout)
      debug:
        msg: "{{ role_cu1.stdout }}"

    - name: Display hasil role .IDFGICU1 (stdout_lines)
      debug:
        var: role_cu1.stdout_lines

    - name: Display hasil role .IDFGICU1 (stderr)
      debug:
        var: role_cu1.stderr

    - name: Simpan hasil ROLE .IDFGICU1 ke artefact
      set_stats:
        data:
          "role_cu1_{{ hostmap[inventory_hostname] | replace('.', '_') }}": "{{ role_cu1.stdout | trim }}"

    - name: Cek role di ENV .IDFGISU1
      shell: |
        source ~/.IDFGISU1
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin
        echo "SET HEADING OFF FEEDBACK OFF; SELECT database_role FROM v\$database;" | sqlplus -s / as sysdba | tr -d '[:space:]'
      register: role_su1
      ignore_errors: true

    - name: Display hasil role .IDFGISU1 (stdout)
      debug:
        msg: "{{ role_su1.stdout }}"

    - name: Display hasil role .IDFGISU1 (stdout_lines)
      debug:
        var: role_su1.stdout_lines

    - name: Display hasil role .IDFGISU1 (stderr)
      debug:
        var: role_su1.stderr

    - name: Simpan hasil ROLE .IDFGISU1 ke artefact
      set_stats:
        data:
          "role_su1_{{ hostmap[inventory_hostname] | replace('.', '_') }}": "{{ role_su1.stdout | trim }}"
