---
- name: Cek ROLE database di DB1 dan DB2 (.IDFGICU1 dan .IDFGISU1)
  hosts: 192.168.1.211,192.168.1.222
  gather_facts: no
  vars:
    hostmap:
      192.168.1.211: db1
      192.168.1.222: db2

  tasks:

    - name: Cek role di ENV .IDFGICU1
      shell: |
        source ~/.IDFGICU1
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin
        echo "SET HEADING OFF FEEDBACK OFF; SELECT database_role FROM v\$database;" \
        | sqlplus -s / as sysdba \
        | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'
      register: role_cu1

    - name: Tampilkan hasil ENV .IDFGICU1
      debug:
        msg: |
          stdout: {{ role_cu1.stdout }}
          stderr: {{ role_cu1.stderr }}
          rc: {{ role_cu1.rc }}

    - name: Simpan hasil ROLE .IDFGICU1 ke artefact
      when: role_cu1.rc == 0 and role_cu1.stdout != ""
      set_stats:
        data:
          "role_cu1_{{ hostmap[inventory_hostname] | replace('.', '_') }}": "{{ role_cu1.stdout | trim }}"

    - name: Cek role di ENV .IDFGISU1
      shell: |
        source ~/.IDFGISU1
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin
        echo "SET HEADING OFF FEEDBACK OFF; SELECT database_role FROM v\$database;" \
        | sqlplus -s / as sysdba \
        | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'
      register: role_su1

    - name: Tampilkan hasil ENV .IDFGISU1
      debug:
        msg: |
          stdout: {{ role_su1.stdout }}
          stderr: {{ role_su1.stderr }}
          rc: {{ role_su1.rc }}

    - name: Simpan hasil ROLE .IDFGISU1 ke artefact
      when: role_su1.rc == 0 and role_su1.stdout != ""
      set_stats:
        data:
          "role_su1_{{ hostmap[inventory_hostname] | replace('.', '_') }}": "{{ role_su1.stdout | trim }}"
