---
- name: Cek ROLE database di DB1 dan DB2 (.IDFGICU1 dan .IDFGISU1)
  hosts: 192.168.1.211,192.168.1.222
  gather_facts: no
  vars:
    hostmap:
      192.168.1.211: db1
      192.168.1.222: db2
  tasks:
    - name: Cek role di ENV .IDFGICU1
      shell: |
        source ~/.IDFGICU1
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin
        echo "SELECT database_role FROM v\$database;" | sqlplus -s / as sysdba | grep "PRIMARY" && echo "PRIMARY" || echo "STANDBY"
      register: role_cu1
      ignore_errors: true

    - name: Debug hasil role CU1 dari host {{ inventory_hostname }}
      debug:
        msg: "{{ role_cu1.stdout }}"

    - name: Simpan hasil ROLE .IDFGICU1 ke artefact
      set_stats:
        data:
          "role_cu1_{{ hostmap[inventory_hostname] | replace('.', '_') }}": "{{ role_cu1.stdout }}"

    - name: Cek role di ENV .IDFGISU1
      shell: |
        source ~/.IDFGISU1
        export ORACLE_HOME=/u01/app/oracle/product/19.3.0/dbhome_1
        export ORACLE_SID=orcl
        export PATH=$PATH:$ORACLE_HOME/bin
        echo "SELECT database_role FROM v\$database;" | sqlplus -s / as sysdba | grep "PRIMARY" && echo "PRIMARY" || echo "STANDBY"
      register: role_su1
      ignore_errors: true

    - name: Debug hasil role SU1 dari host {{ inventory_hostname }}
      debug:
        msg: "{{ role_su1.stdout }}"

    - name: Simpan hasil ROLE .IDFGISU1 ke artefact
      set_stats:
        data:
          "role_su1_{{ hostmap[inventory_hostname] | replace('.', '_') }}": "{{ role_su1.stdout }}"
