---
- name: CEK ROLE DB1 untuk .IDFGICU1 dan .IDFGISU1
  hosts: 192.168.1.211
  tasks:
    - name: Cek role DB1 dari .IDFGICU1
      shell: |
        . ~/.IDFGICU1
        echo "SELECT database_role FROM v\$database;" | sqlplus -s / as sysdba
      register: db1_cu1_role

    - name: Cek role DB1 dari .IDFGISU1
      shell: |
        . ~/.IDFGISU1
        echo "SELECT database_role FROM v\$database;" | sqlplus -s / as sysdba
      register: db1_su1_role

- name: CEK ROLE DB2 untuk .IDFGICU1 dan .IDFGISU1
  hosts: 192.168.1.222
  tasks:
    - name: Cek role DB2 dari .IDFGICU1
      shell: |
        . ~/.IDFGICU1
        echo "SELECT database_role FROM v\$database;" | sqlplus -s / as sysdba
      register: db2_cu1_role

    - name: Cek role DB2 dari .IDFGISU1
      shell: |
        . ~/.IDFGISU1
        echo "SELECT database_role FROM v\$database;" | sqlplus -s / as sysdba
      register: db2_su1_role
