---
- name: Cek env .IDFGISU1 Primary
  hosts: localhost
  vars:
    primary_db_su1: "DB1"
    standby_db_su1: "DB2"
  tasks:
    - name: "Tampilkan data dari PRIMARY"
      debug:
        msg: "{{ primary_db_su1 }}"
        
    - name: "Tampilkan data dari STANDBY"
      debug:
        msg: "{{ standby_db_su1 }}"

    - name: "Cek apakah primary_db adalah DB1"
      assert:
        that:
          - primary_db_su1 == 'DB1'
        fail_msg: "Pengecekan gagal: primary_db_su1 bukan DB1"
        success_msg: "Pengecekan berhasil: primary_db_su1 adalah DB1"

    - name: "Cek apakah standby_db adalah DB2"
      assert:
        that:
          - standby_db_su1 == 'DB2'
        fail_msg: "Pengecekan gagal: standby_db_su1 bukan DB2"
        success_msg: "Pengecekan berhasil: standby_db_su1 adalah DB2"
