---
- name: ACTION PENJODOHAN 2 (ENV .IDFGISU1)
  hosts: localhost
  tasks:
    - name: Ambil switchover_status dari DB1 dan DB2 jika DB1 Primary
      when:
        - "'PRIMARY' in hostvars['192.168.1.211']['db1_role']"
        - "'PHYSICAL STANDBY' in hostvars['192.168.1.222']['db2_role']"
      block:
        - name: Switchover status dari DB1
          shell: |
            ssh oracle@192.168.1.211 "source ~/.IDFGISU1; echo 'SELECT switchover_status FROM v\\$database;' | sqlplus -s / as sysdba"
          register: switchover_db1

        - name: Switchover status dari DB2
          shell: |
            ssh oracle@192.168.1.222 "source ~/.IDFGISU1; echo 'SELECT switchover_status FROM v\\$database;' | sqlplus -s / as sysdba"
          register: switchover_db2

    - name: Ambil switchover_status dari DB2 dan DB1 jika DB2 Primary
      when:
        - "'PRIMARY' in hostvars['192.168.1.222']['db2_role']"
        - "'PHYSICAL STANDBY' in hostvars['192.168.1.211']['db1_role']"
      block:
        - name: Switchover status dari DB2
          shell: |
            ssh oracle@192.168.1.222 "source ~/.IDFGISU1; echo 'SELECT switchover_status FROM v\\$database;' | sqlplus -s / as sysdba"
          register: switchover_db2

        - name: Switchover status dari DB1
          shell: |
            ssh oracle@192.168.1.211 "source ~/.IDFGISU1; echo 'SELECT switchover_status FROM v\\$database;' | sqlplus -s / as sysdba"
          register: switchover_db1
