---
- name: Switchover Status Check from source and target
  hosts: "{{ source_db }}"
  tasks:
    - name: Cek switchover_status dari source DB
      shell: |
        . ~/{{ profile_env }}
        echo "SELECT switchover_status FROM v\$database;" | sqlplus -s / as sysdba
      register: sw_status_src

    - name: Tampilkan status switchover source
      debug:
        msg: "Source ({{ source_db }}) switchover_status: {{ sw_status_src.stdout }}"

- name: Switchover Status Check from target
  hosts: "{{ target_db }}"
  tasks:
    - name: Cek switchover_status dari target DB
      shell: |
        . ~/{{ profile_env }}
        echo "SELECT switchover_status FROM v\$database;" | sqlplus -s / as sysdba
      register: sw_status_tgt

    - name: Tampilkan status switchover target
      debug:
        msg: "Target ({{ target_db }}) switchover_status: {{ sw_status_tgt.stdout }}"
